name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt
      run: sudo apt update
    - name: dependencies
      run: sudo apt install build-essential libncurses-dev postgresql-common postgresql-server-dev-16
    - name: make
      run: make
